### ISSUE TITLE
Dead webhook(s) for buildkite pipelines "shale" and "shale-rtl"

### ISSUE THREAD

**Issue by steveri** [THofstee/shale#12]
I am in the process of killing dead/unused buildkite pipelines. One or more of these pipelines had webhooks pointing to this repo, if so they would be listed here:

<p>https://github.com/StanfordAHA/garnet/settings/hooks => edit => payload URL

Two pipelines were deleted:

**Deleted buildkite pipeline** https://buildkite.com/tapeout-aha/shale
**Payload URL**
https://webhook.buildkite.com/deliver/b099802108458d6bdd84a8f4301f21b19f6cd2c3d8aa9d09d1
**(Deleted) pipeline steps:**
```
env:
  COMMIT: $(git rev-parse --verify HEAD)
  APP: apps/conv_3_3/conv_3_3_opt
  
steps:
  - commands:
    - exit
    - echo "--- Setting up environment"
    - pushd .
    - export SHALE_ROOT=`pwd`
    - export PATH=/sim/miniconda/bin:\$PATH
    - source /cad/modules/tcl/init/sh
    - module load base vcs
    - pip install --user virtualenv
    - python -m virtualenv $COMMIT
    - source $COMMIT/bin/activate
    - cd deps/garnet
    - git checkout flow
    - git pull
    - pip install -r requirements.txt
    - cd ../..
    - pip install deps/jmapper*
    - pip install -e .
    - echo "--- Dependencies"
    - pip list
    - echo "--- Creating testbenches"
    - cp /sim/latest/garnet/garnet.v deps/garnet/garnet.v
    - python run.py --width 32 --height 16 --dry-run $APP 2>&1 | sed 's/---/===/'
    - python run.py --width 32 --height 16 --skip-garnet $APP 2>&1 | sed 's/---/===/'
    - ls $APP
    - echo "--- Running tests"
    - cd $APP/test
          # -v /sim/latest/garnet/tapeout_16/synth/GarnetSOC_pad_frame/pnr.final.gls.v \
    - |
      make SIM=vcs VERILOG_SOURCES="\$SHALE_ROOT/extras/garnet_top.sv" \
      COMPILE_ARGS="\
          -v /sim/thofstee/aha-arm-soc-june-2019/implementation/synthesis/synth/GarnetSOC_pad_frame/results_syn/syn_out.v \
          -v /sim/latest/garnet/tapeout_16/synth/Tile_PE/pnr.v \
          -v /sim/latest/garnet/tapeout_16/synth/Tile_MemCore/pnr.v \
          `find /tsmc16/TSMCHOME/digital/Front_End/verilog/ -name '*.v' | grep -v "pwr" | sed -e 's/^/-v /' | xargs` \
          `find /sim/ajcars/mc -name '*.v' | grep -v pwr | sed -e 's/^/-v /' | xargs`"
    # - make SIM=vcs VERILOG_SOURCES="/" COMPILE_ARGS="-sdf max:Garnet:/"
    # TESTCASE="test_tile" COMPILE_ARGS="-sdf max:Tile_MemCore:/home/thofstee/pnr_10-31.sdf +sdfverbose +overlap +multisource_int_delays +neg_tchk -negdelay" TOPLEVEL="Tile_MemCore" TRACE="linebuffer_bank_0_0.csv" ^&1 | tee vcs.log 
    agents:
    - "queue=papers"
```
**Deleted buildkite pipeline** https://buildkite.com/tapeout-aha/shale-rtl
**Payload URL**
https://webhook.buildkite.com/deliver/52df3860241f6f6d99fd5427ca7321c0facc8381a5dce01aab
**(Deleted) pipeline steps:**
```
env:
  COMMIT: $(git rev-parse --verify HEAD)
  APP: apps/conv_3_3/conv_3_3_opt
  # TILE: Tile_X04_Y02
  # TILETYPE: Tile_PE
  WIDTH: 12
  HEIGHT: 4
  
steps:
  - commands:
    - echo \"--- Skipping pipeline\"
    - exit
    - echo \"--- Setting up environment\"
    - pushd .
    - export SHALE_ROOT=`pwd`
    - mkdir -p /sim/shale-rtl/$COMMIT
    - export PATH=/sim/miniconda/bin:\$PATH
    - source /cad/modules/tcl/init/sh
    - module load base vcs
    - pip install --user virtualenv
    - python -m virtualenv $COMMIT
    - source $COMMIT/bin/activate
    - cd deps/garnet
    - git checkout flow
    - git pull
    - pip install -r requirements.txt
    - cd ../..
    - pip install deps/jmapper*
    - pip install -e .
    - cp /cad/cadence/GENUS17.21.000.lnx86/share/synth/lib/chipware/sim/verilog/CW/CW_tap.v extras/CW_tap.v
    - echo \"--- Dependencies\"
    - pip list
    - echo \"--- Creating testbenches\"
    - cp /sim/latest/garnet/garnet.v deps/garnet/garnet.v
    - python run.py --width $WIDTH --height $HEIGHT --dry-run $APP 2>&1 | sed 's/---/===/'
    - python run.py --width $WIDTH --height $HEIGHT $APP --force 2>&1 | sed 's/---/===/'
    - echo \"--- Running tests\"
    - cd $APP/test
    - make SIM=vcs
    - for ((w=0; w<$WIDTH; w++)); do
        for ((h=1; h<=$HEIGHT; h++)); do
          TILE=$(printf \"Tile_X%02X_Y%02X\n\" $$w $$h);
          if (($$h == 0)); then
            TILETYPE=\"Tile_io_core\";
          elif (($$w%4 == 3)); then
            TILETYPE=\"Tile_MemCore\";
          else
            TILETYPE=\"Tile_PE\";
          fi;
          echo \"---\" $$TILE $$TILETYPE;
          make SIM=vcs clean;
          make SIM=vcs
            TESTCASE=\"test_tile\"
            TOPLEVEL=\"$$TILETYPE\"
            TRACE=\"$$TILE.csv\"
            VERILOG_SOURCES=\"/sim/latest/garnet/tapeout_16/synth/$$TILETYPE/pnr.v\"
            COMPILE_ARGS=\"
              +vcs+dumpvars+$$TILE.vcd
              -sdf max:$$TILETYPE:'/sim/latest/garnet/tapeout_16/synth/$$TILETYPE/final.sdf'
              +sdfverbose +overlap +multisource_int_delays +neg_tchk -negdelay
              `find /tsmc16/TSMCHOME/digital/Front_End/verilog/ -name '*.v' | grep -v \"pwr\" | sed -e 's/^/-v /' | xargs`
              `find /sim/ajcars/mc -name '*.v' | grep -v pwr | sed -e 's/^/-v /' | xargs`\";
        done;
      done
    - echo \"--- Reporting power\"
    - cd $$SHALE_ROOT/power
    - for ((w=0; w<$WIDTH; w++)); do
        for ((h=1; h<=$HEIGHT; h++)); do
          TILE=$(printf \"Tile_X%02X_Y%02X\n\" $$w $$h);
          if (($$h == 0)); then
            TILETYPE=\"Tile_io_core\";
          elif (($$w%4 == 3)); then
            TILETYPE=\"Tile_MemCore\";
          else
            TILETYPE=\"Tile_PE\";
          fi;
          env BASE=$$SHALE_ROOT/$APP/test APP=$$TILE DESIGN=$$TILETYPE T_0=$(cat $$SHALE_ROOT/$APP/test/t_start) T_1=$(cat $$SHALE_ROOT/$APP/test/t_end) ./run.sh;
        done;
      done
    - python application.py $$SHALE_ROOT/$APP --width $WIDTH --height $HEIGHT --reports reports
    - echo \"--- Uploading results\"
    - rsync -av --exclude=.git --exclude=$COMMIT --exclude=__pycache__ $$SHALE_ROOT /sim/shale-rtl/$COMMIT/shale
    # - make SIM=vcs clean
    # - make SIM=vcs
    #     TESTCASE=\"test_tile\"
    #     TOPLEVEL=\"$TILETYPE\"
    #     TRACE=\"$TILE.csv\"
    #     VERILOG_SOURCES=\"/sim/latest/garnet/tapeout_16/synth/$TILETYPE/pnr.v\"
    #     COMPILE_ARGS=\"
    #       +vcs+dumpvars+$TILE.vcd
    #       -sdf max:$TILETYPE:'/sim/latest/garnet/tapeout_16/synth/$TILETYPE/final.sdf'
    #       +sdfverbose +overlap +multisource_int_delays +neg_tchk -negdelay
    #       `find /tsmc16/TSMCHOME/digital/Front_End/verilog/ -name '*.v' | grep -v \"pwr\" | sed -e 's/^/-v /' | xargs`
    #       `find /sim/ajcars/mc -name '*.v' | grep -v pwr | sed -e 's/^/-v /' | xargs`\"
    agents:
    - \"queue=papers\"
```
